### ISSUE TITLE
tars cpp使用的是 STATUS_TRACK_KEY，而这里的实现是 STATUS_TRACE_KEY

### ISSUE THREAD

**Issue by funkyLover** [tars-node/opentelemetry-instrumentation-tars#1]
我看[tars cpp](https://github.com/TarsCloud/TarsCpp/search?q=STATUS_TRACK_KEY)的实现中，是使用 `STATUS_TRACK_KEY` 作为 key 来获取/设置 span 内容

而这里的[实现](https://github.com/tars-node/opentelemetry-instrumentation-tars/blob/master/src/tars/constants.ts#L11)，使用的是`STATUS_TRACE_KEY` 

这应该只是笔误吧？如果不是的话，是否考虑提供 api 来支持 trace key 的自定义

**Comment by funkyLover** [comment]
翻了一下，原来是版本问题，之前CPP版本用的是 STATUS_TRACK_KEY，现在已经都改成 STATUS_TRACE_KEY了

Emm....有点尴尬，现在我们服务端用的是之前的版本的 tars cpp，已经用的是 `STATUS_TRACK_KEY` 了

现在 nodejs 的 tars client 还是希望尽量也能用 `STATUS_TRACK_KEY`

除了fork一份之后改源码之外还有没有其他方式没，不知能否提供一些建议？

**Comment by shevqko** [comment]
你在框架里面， 再加个 string ServantProxy::STATUS_TRACE_KEY     = "STATUS_TRACE_KEY"; 的定义？ 
即两种key 都能兼容 ？

**Comment by ruanshudong** [comment]
你在用调用链么? 新版本tarscpp和nodejs都全新写了调用链, 所以这个变量改了名字

**Comment by zouchengzhuo** [comment]
> 

这个版本的实现是往新版的 tars trace 里边上报调用量，我不确定和你之前用的是不是同一套上报。 可以fork修改后调试试一下，如果可以也可也提个pr我们来合并呀~
